#!/usr/bin/env bash
# test/compat/audit.sh
# Diff `docker <verb> --help` vs `gocker <verb> --help` for every verb,
# produce a markdown matrix flagging gaps. Runs fully offline (just --help).
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

: "${DOCKER:=docker}"
: "${GOCKER:=gocker}"
: "${OUTPUT:=$REPO_ROOT/docs/docker-compatibility-matrix.md}"

IGNORED_FILE="$SCRIPT_DIR/ignored.txt"

# Fail fast if docker isn't available.
if ! command -v "$DOCKER" >/dev/null 2>&1; then
    echo "error: DOCKER ($DOCKER) not found on PATH; install Docker CLI or set DOCKER=<path>" >&2
    exit 2
fi
if ! command -v "$GOCKER" >/dev/null 2>&1; then
    echo "error: GOCKER ($GOCKER) not found on PATH; build it or set GOCKER=<path>" >&2
    exit 2
fi

# Extract top-level verbs from `<cmd> --help` output. urfave/cli and docker's
# help formats both list subcommands under a COMMANDS: section.
top_level_verbs() {
    local cmd="$1"
    "$cmd" --help 2>/dev/null \
        | awk '/^(COMMANDS|Commands):/{flag=1; next} /^[A-Z][A-Z]+:/{flag=0} flag && /^[[:space:]]+[a-z]/{print $1}' \
        | sort -u
}

is_ignored() {
    local verb="$1"
    [ -f "$IGNORED_FILE" ] && grep -qxF "$verb" "$IGNORED_FILE"
}

gocker_has_flag() {
    local verb="$1"; local flag="$2"
    "$GOCKER" "$verb" --help 2>/dev/null | grep -qE "^\s+${flag}\b"
}

extract_flags() {
    local cmd="$1"; local verb="$2"
    "$cmd" "$verb" --help 2>/dev/null \
        | awk '/^OPTIONS:|^Options:/{flag=1; next} /^[A-Z][A-Z]+:/{flag=0} flag' \
        | grep -oE -- '-[-[:alnum:]]+' \
        | sort -u
}

{
    echo "# Docker Compatibility Matrix"
    echo
    echo "_Generated by \`test/compat/audit.sh\`. Do not edit by hand._"
    echo
    echo "_Source: \`$DOCKER --help\` and \`$GOCKER --help\`._"
    echo
    echo "Legend: ✅ present, ❌ missing, ➖ ignored (see \`test/compat/ignored.txt\`)"
    echo
    echo "## Top-level commands"
    echo
    echo "| docker verb | gocker status | notes |"
    echo "|---|---|---|"

    for verb in $(top_level_verbs "$DOCKER"); do
        if is_ignored "$verb"; then
            echo "| \`$verb\` | ➖ ignored | deliberately not supported |"
            continue
        fi
        if "$GOCKER" "$verb" --help >/dev/null 2>&1; then
            echo "| \`$verb\` | ✅ present | — |"
        else
            echo "| \`$verb\` | ❌ missing | no \`gocker $verb\` |"
        fi
    done

    echo
    echo "## Flag diff for shared commands"
    echo
    echo "| command | docker flags gocker lacks |"
    echo "|---|---|"

    for verb in $(top_level_verbs "$DOCKER"); do
        if is_ignored "$verb"; then continue; fi
        if ! "$GOCKER" "$verb" --help >/dev/null 2>&1; then continue; fi
        missing=""
        for flag in $(extract_flags "$DOCKER" "$verb"); do
            if ! gocker_has_flag "$verb" "$flag"; then
                missing="$missing \`$flag\`"
            fi
        done
        missing="${missing# }"
        if [ -n "$missing" ]; then
            echo "| \`$verb\` | $missing |"
        fi
    done
} > "$OUTPUT"

echo "wrote $OUTPUT"
